server:
  port: 8095
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heapix-task-1-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: shundrikaleksey@gmail.com
    password: '!Islonimski_sokI!'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      hibernate:
        SQL: debug

auth:
  token:
    key: inst
